name: 'Environment Variable Substitutor'
description: 'Substitute ${prefix.VAR} placeholders with environment variables'
author: 'Udit Patel <udit014patel@gmail.com'
branding:
  icon: 'edit-3'
  color: 'purple'

inputs:
  files:
    description: 'Comma-separated list of files to process'
    required: true
  placeholder-prefix:
    description: '3-character prefix (e.g., env)'
    required: true
    default: 'env'
  destination-path:
    description: 'Custom output directory (optional)'
  create-dirs:
    description: 'By default create directories if not exists '
    default: true
  dry-run:
    description: 'Verify the expected out without creating files'
    default: false
runs:
  using: "composite"
  steps:
    - name: "Dynamic Variable Substitution"
      env:
        FILES: ${{ inputs.files }}
        PREFIX: ${{ inputs.placeholder-prefix }}
        DEST_PATH: ${{ inputs.destination-path }}
        CREATE_DIRS: ${{ inputs.create-dirs }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        bash "${{ github.action_path }}/scripts/variable_substitutor.sh"
      shell: bash
