name: Unit Test Action

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  Test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      actions: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Install Dependencies
      #        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Run Tests
        run: |
          chmod +x tests/test_variable_substitutor.sh
          bash $GITHUB_WORKSPACE/tests/test_variable_substitutor.sh
        shell: bash

#      - name: Upload Artifacts
#        if: ${{ failure() }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: |
#            test_files/
#            test_output/