name: Unit Test Action

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  Test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      actions: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Install Dependencies
      #        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Run Tests
        run: |
          chmod +x tests/test_variable_substitutor.sh
          tests/test_variable_substitutor.sh

      - name: Upload Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test_files/
            test_output/