name: Example Test Action

on:
  workflow_run:
    workflows: [ "Unit Test Action" ]
    types:
      - completed

  workflow_dispatch:

jobs:
  Example_Test_Action:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


#      - name: Install Dependencies
#        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Test Substitution
        uses: ./
        with:
          files: "${{ github.workspace }}/tests/ActionCheck/sample-config.txt"
          placeholder-prefix: 'vst'
          dry-run: true
        env:
          APP_NAME: "Substitutor"
          APP_VERSION: "V1"

#            - name: Test Prep
#              run: |
#                mkdir -p "$GITHUB_WORKSPACE/tests/ActionCheck/"
#                chmod -R 777 "$GITHUB_WORKSPACE/tests"
#                echo '"Hello from ${vst.APP_NAME} ___ ${vst.APP_VERSION}" > ./tests/ActionCheck/sample-config.txt'
#                ls -l
#                ls -ld "$GITHUB_WORKSPACE/tests/ActionCheck"
#                whoami