name: CI Test Action

on:
  workflow_run:
    workflows: [ "Unit Test Action" ]
    types:
      - completed

  workflow_dispatch:

jobs:
  Example_Test_Action:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    permissions:
      actions: write
      contents: write

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


#      - name: Install Dependencies
#        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Test Substitution
        uses: ./
        with:
          files: "tests/ActionCheck/sample-config.txt"
          placeholder-prefix: 'vst'
          dry-run: true
        env:
          APP_NAME: "Substitutor"
          APP_VERSION: "V1"

      - name: Test Substitution with destination dir
        uses: ./
        with:
          files: "tests/ActionCheck/sample-config.txt"
          placeholder-prefix: 'vst'
          destination-path: "tests/ActionValid/valid-config.txt"

        env:
          APP_NAME: "Substitutor"
          APP_VERSION: "V1"

      - name: Test Substitution with Default prefix
        uses: ./
        with:
          files: "tests/ActionCheck/sample-config-default-prefix.txt"
          destination-path: "tests/ActionValid/valid-config-default-prefix.txt"

        env:
          APP_NAME: "Substitutor"
          APP_VERSION: "V1"
